### ISSUE TITLE
Menu bugando em celulares

### ISSUE THREAD

**Issue by iagogutierre** [coolabnet/site#10]
No projeto em html o menu está funcionando normal, mas quando implementado no tema apresentou alguns problemas. Provavelmente deve estar faltando alguma marcação ou regra de estilo.

**Comment by hiurequeiroz** [comment]
quais os problemas? aqui para mim ele abre do lado direito, mas funcionou tudo certinho

**Comment by iagogutierre** [comment]
Ele parou de fazer o dropdown quando implementei no wp e abri no celular. 

![screenshot_2018-09-26 coolab](https://user-images.githubusercontent.com/2375521/46113743-f8b30500-c1c5-11e8-8572-737c6ce6a8f5.png)

**Comment by hiurequeiroz** [comment]
cara desculpa, eu to querendo ajudar mas to bem por fora. Ao invés de index.html deveria ser index.php? como que eu faço isso aqui para testar?
