### ISSUE TITLE
Falta formulário de contato

### ISSUE THREAD

**Issue by brunovianna** [coolabnet/site#27]
https://www.coolab.org/contato.html

**Comment by brunovianna** [comment]
O plugin contact form não funciona. Vamos usar o https://www.coolab.org/wp-admin/admin.php?page=wpforms-builder

**Comment by iagogutierre** [comment]
Utilizei o plugin wpforms para criar um form de contato. 
Esta disponivel atraves do link https://www.coolab.org/contato/
