### ISSUE TITLE
Fontes erradas nos posts

### ISSUE THREAD

**Issue by brunovianna** [coolabnet/site#28]
As fontes de textos nos posts não são as que estão no design original. 

Exemplo: https://www.coolab.org/2019/09/regulamento-concurso-de-videos/
E o design é assim: https://xd.adobe.com/spec/968970e4-b9aa-4108-7196-8575f4320494-e0b8/screen/982d5863-9bcd-4958-a7b4-beb19988f37b/05-1-Blog-Post

(fui eu que programei isso...)

**Comment by brunovianna** [comment]
o design completo está aqui: https://xd.adobe.com/spec/968970e4-b9aa-4108-7196-8575f4320494-e0b8/grid

**Comment by iagogutierre** [comment]
Era um 't' que ficou faltando no  font-family, acho que acabei alterando pela dashboard mesmo.
