### ISSUE TITLE
Verificar a cor dos menus

### ISSUE THREAD

**Issue by iagogutierre** [coolabnet/site#9]
Existem dois menus declarados no arquivo functions.php como: 'menu_coolab' e 'menu_coolab_preto'. A única diferença entre eles é a cor de background. Na front-page precisamos exibir o menu_coolab ao invés do menu_coolab_preto, como está sendo exibido.

**Comment by hiurequeiroz** [comment]
oxe aqui ta aparecendo branco

**Comment by iagogutierre** [comment]
Confere na dashboard se você criou o menu e as respectivas páginas. Na criação das páginas, cada uma possui um modelo proprio com o mesmo nome. Cria uma pagina com nome projetos e usa o modelo projetos, por exemplo.

**Comment by hiurequeiroz** [comment]
A não eu acho que eu estou na versão html. Desculpa, eu acho que não fiz algum passo básico ai né?

**Comment by iagogutierre** [comment]
Pior que ta meio confuso, vou fazer um passo a passo de como instalar o tema e compartilho na wiki.
